### ISSUE TITLE
Rotation Filter Error

### ISSUE THREAD

**Issue by WearifulCupid0** [2d-archive/lavalink#3]
Java: 13
Lavaplayer: 1.3.66
```
2021-01-29T17:42:10.329975+00:00 app[web.1]: 2021-01-29 17:42:10.329  INFO 25 --- [   XNIO-1 I/O-5] lavalink.server.io.SocketServer          : {"rotation":{"speed":"0.1f"},"op":"filters","guildId":"777332295836368917"}
2021-01-29T17:42:10.440475+00:00 app[web.1]: 2021-01-29 17:42:10.440  INFO 25 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$614/0x00000008011b9440@39483df5
2021-01-29T17:42:10.441797+00:00 app[web.1]: 2021-01-29 17:42:10.441  INFO 25 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: loading with filter null
2021-01-29T17:42:10.455086+00:00 app[web.1]: 2021-01-29 17:42:10.454 ERROR 25 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: loading failed.
2021-01-29T17:42:10.455087+00:00 app[web.1]: 
2021-01-29T17:42:10.455089+00:00 app[web.1]: java.lang.UnsatisfiedLinkError: Required library was not found
2021-01-29T17:42:10.455090+00:00 app[web.1]: 	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:125) ~[lava-common-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455090+00:00 app[web.1]: 	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadInternal(NativeLibraryLoader.java:110) ~[lava-common-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455091+00:00 app[web.1]: 	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:84) ~[lava-common-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455091+00:00 app[web.1]: 	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:69) ~[lava-common-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455092+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455093+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.getInstance(OpusDecoderLibrary.java:14) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455093+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:20) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455093+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:194) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455094+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:178) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455095+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:94) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455095+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:47) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455096+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:372) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455096+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:336) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455097+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:321) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455097+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:297) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455098+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:40) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455098+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:276) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455098+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:250) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455099+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:39) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455099+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455100+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455100+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455101+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455101+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:351) ~[lavaplayer-1.3.66-20-SNAPSHOT.jar!/:na]
2021-01-29T17:42:10.455108+00:00 app[web.1]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
2021-01-29T17:42:10.455109+00:00 app[web.1]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
2021-01-29T17:42:10.455109+00:00 app[web.1]: 	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
```

**Comment by WearifulCupid0** [comment]
Bruh already found the error.
